### ISSUE TITLE
Does Netopeer2GUI support Netopeer2-v2.1.42?

### ISSUE THREAD

**Issue by rydy** [CESNET/Netopeer2GUI#25]
Hi,

Does Netopeer2GUI support [Netopeer2-v2.1.42](https://github.com/CESNET/netopeer2/releases/tag/v2.1.42)?

Thanks,
Best regards.

**Comment by jakubman1** [comment]
Hello.

Sorry, but this project is currently not maintained, so I can not guarantee that it would support the newest version of Netopeer2. I can not recommend using the GUI in production since the liberouter-gui framework is abandoned and might contain security issues.

However, the GUI might work with the newest Netopeer2 since it uses libyang and libnetconf to send NETCONF messages, not Netopeer2 itself. 

Sorry again that I could not help you more.

Best regards,
Jakub.

**Comment by rydy** [comment]
> Hello.
> 
> Sorry, but this project is currently not maintained, so I can not guarantee that it would support the newest version of Netopeer2. I can not recommend using the GUI in production since the liberouter-gui framework is abandoned and might contain security issues.
> 
> However, the GUI might work with the newest Netopeer2 since it uses libyang and libnetconf to send NETCONF messages, not Netopeer2 itself.
> 
> Sorry again that I could not help you more.
> 
> Best regards, Jakub.

I see, Thanks.
