### ISSUE TITLE
Provide UI response for backend or yang parsing failure

### ISSUE THREAD

**Issue by jgroom33** [CESNET/Netopeer2GUI#5]
Current behavior:
Currently, when a backend failure occurs, the UI redirects to the login prompt.

Desired behavior:
UI should provide failure reason (yang parsing or backend failure)
UI should provide a way to show the logs of the backend parsing result

**Comment by rkrejci** [comment]
Can you be more specific?

You describe our goal, there is a number of situation when the backend detects problem, replies to the frontend with error description and frontend presents it to users. Unfortunatelly, there is also still a number of situation when the backend crashes (usually because of not handled exception). It is not intended, but to fix it we need the description of what happened / steps to reproduce. I don't see any of it in this issue, so from my point of view the issue can be understood as `drive safely` - true but little useless.
